### ISSUE TITLE
Wrap text of CheckDataModel

### ISSUE THREAD

**Issue by polarby** [ritagroup/gsform#1]
When using long texts in ` GSField.checkList` widget, it will cause 
```
A RenderFlex overflowed by x pixels on the right.
```
Simply wrapping and making the checkbox field bigger would be awesome. Otherwise longer texts such as Term agreements cannot be displayed on the mobile version.

**Comment by saeeddastras** [comment]
We fixed this problem in version 0.1.4 .
Tanks for your attention.
