### ISSUE TITLE
Get seletected Date from  GSField.datePicker

### ISSUE THREAD

**Issue by gang-10** [ritagroup/gsform#10]
Hello 
i am using gsform Flutter , when the date is select i can run a callback Function or when submit form i cant get the date seletected 
Helps --¨?

**Comment by saeeddastras** [comment]
Hello 

you can get data of field  by using field tag 


 ```
GSField.datePicker(
                      tag: 'date',
                      calendarType: GSCalendarType.gregorian,
                      title: 'DatePicker',
                      weight: 12,
                      required: false,
                      errorMessage: 'please enter a name',
                    ),
```
var date = `Map<String, dynamic> map = form.onSubmit()['date'];// get value of form data by tag
`

**Comment by saeeddastras** [comment]
Hello 

you can get data of field  by using field tag 


 ```
GSField.datePicker(
                      tag: 'date',
                      calendarType: GSCalendarType.gregorian,
                      title: 'DatePicker',
                      weight: 12,
                      required: false,
                      errorMessage: 'please enter a name',
                    ),
```
var date = `Map<String, dynamic> map = form.onSubmit()['date'];// get value of form data by tag
`

**Comment by gang-10** [comment]
it s works like a charm
tks a lot
