### ISSUE TITLE
Error: Either zero or 2 or more [DropdownMenuItem]s

### ISSUE THREAD

**Issue by gang-10** [ritagroup/gsform#11]
hello i am using GSFORM dropdownlist 
i get this error when using 2  GSField.spinner

Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
dropdown.dart:1
Failed assertion: line 890 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

**Comment by saeeddastras** [comment]
hello @gang-10  
Please send me more details of your code so that I can investigate your problem more closely

**Comment by gang-10** [comment]
hello saeeddastras 

`GSField.spinner(
                                tag: 'prospect_prospect',
                                required: true,
                                weight: 12,
                                title: 'Prospect',
                                onChange: (model) {
                                  print(model?.name.toString());
                                },
                                items: [
                                  SpinnerDataModel(
                                    name: 'Clients SBBC',
                                    id: 1,
                                  ),
                                  SpinnerDataModel(
                                    name: 'Nouveau CLient',
                                    id: 2,
                                    isSelected: true,
                                  ),
                                ],
                              ),
                              GSField.spinner(
                                tag: 'concurrent_prospect',
                                required: true,
                                weight: 6,
                                title: 'Concurrent ',
                                onChange: (model) {
                                  print(model?.name.toString());
                                },
                                items: [
                                  SpinnerDataModel(
                                    name: 'OroBrique',
                                    id: 1,
                                  ),
                                  SpinnerDataModel(
                                    name: 'SolaBriq',
                                    id: 2,
                                  ),
                                  SpinnerDataModel(
                                    name: 'Jbel Annour',
                                    id: 3,
                                  ),
                                  SpinnerDataModel(
                                    name: 'Menara Briques',
                                    id: 4,
                                  ),
                                  SpinnerDataModel(
                                    name: 'Aya Brique',
                                    id: 5,
                                    isSelected: true,
                                  ),
                                ],
                              ),`
There should be exactly one item with [DropdownButton]'s value: Instance of 'SpinnerDataModel'. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
dropdown.dart:1
Failed assertion: line 890 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

**Comment by saeeddastras** [comment]
Hello
I checked the code you sent and I didn't see any problem with it and it ran without any problem
