### ISSUE TITLE
DatePicker Date vanishes on a refresh

### ISSUE THREAD

**Issue by MarkKuzmycz** [ritagroup/gsform#12]
When I save a form the form is pre-rendered with the saved valued. (The reason for this is that the object used to initialise the form is a stream object. So a change to the object and a change to the entire form ) For the date picker field, it goes blank and if you select the field the picker gives an error stating "Field 'gregorianInitialDate' has not been initialized" .

`              GSField.datePicker(
                tag: "surveyExpiry",
                title: "Survey Expiry",
                initialDate: toGSDate(vessel?.surveyExpiry),
                calendarType: GSCalendarType.gregorian,),
`

`GSDate toGSDate(DateTime? value) {
    value ??= DateTime.now();

    return GSDate(year: value!.year, month: value!.month, day: value!.day);
  }`

comment:  the attributes (initialDate, availableFrom, availableTo) should be initialised in GSDatePickerField not _GSDatePickerFieldState. This change would allow the values to be changed dynamically.

**Comment by saeeddastras** [comment]
This problem is solved, please update the version to the latest version
