### ISSUE TITLE
Settings to make all Checkboxes required 

### ISSUE THREAD

**Issue by polarby** [ritagroup/gsform#2]
When using the parameter `required` on `GSField.checkList`, it will only enforce one check mark to be checked. Is there an option to request that all are checked?
```
GSField.checkList(
          required: true,
          items: [
            ...
          ],
          callBack: (CheckDataModel value) {},
        ),
```

The best case would be if there is a `required` parameter on `CheckDataModel`, so i can set each Checkbox that should be required.

**Comment by saeeddastras** [comment]
We have changed the structure in `required `for `GSField.checkList` to solve your problem so that you can use  
  `requiredCheckListEnum` Instead of  `required  `to check all item are selected 

```  
GSField.checkList(
          requiredCheckListEnum: RequiredCheckListEnum.all,
          items: [
            ...
          ],
          callBack: (CheckDataModel value) {},
        ), 
```

**Comment by polarby** [comment]
I highly appreciate it! Thanks a lot you guys! You are awesome and really fast. Great work!
