### ISSUE TITLE
gsform builder dependancy conflict with image picker

### ISSUE THREAD

**Issue by hupochuanYoung** [ritagroup/gsform#20]
1.

<img width="1391" alt="image" src="https://github.com/ritagroup/gsform/assets/57694784/2e109d51-db71-4a0a-bf42-5c9670f2263d">

2.
<img width="1024" alt="image" src="https://github.com/ritagroup/gsform/assets/57694784/4b3d70de-44a6-454c-966a-69215f337980">

**Comment by saeeddastras** [comment]
Hello 
please update version of gsform
