### ISSUE TITLE
email validation error

### ISSUE THREAD

**Issue by hupochuanYoung** [ritagroup/gsform#21]
```  
GSField.email(
                    tag: 'email',
                    title: getTranslated('login_hint', context)!,
                    weight: 12,
                    required: true,
                    maxLength: 100,
                    prefixWidget:const Icon(FontAwesomeIcons.envelope,size: 15,),
                    errorMessage:  getTranslated('invalid_email', context)!,
                  ),
```

whatever I type, even if I type my email account, the validation always returns an error.

<img width="391" alt="image" src="https://github.com/ritagroup/gsform/assets/57694784/8fa3cc14-ded0-404d-879e-697287b8ce57">
<img width="837" alt="Screenshot 2024-04-11 at 20 35 17" src="https://github.com/ritagroup/gsform/assets/57694784/389e7d0a-bc9b-4c90-8fbc-d57f1cffe483">

**Comment by saeeddastras** [comment]
Hello @Amber916Young  we fix this bug 
 you can update  version of GSForm and use it

**Comment by hupochuanYoung** [comment]
Hi, the pub version is still   ^0.3.5, which is the lasted version? Thank you very much.

**Comment by saeeddastras** [comment]
In a few minutes, the new version will be loaded and you can use it

Thanks
