### ISSUE TITLE
[Help] Return value of GSField.spinner

### ISSUE THREAD

**Issue by polarby** [ritagroup/gsform#3]
I am trying to get the value of the spinner widget. Unfortunately, I will only get the `Instance of 'SpinnerDataModel'` in my json.

```dart
GSField.spinner(
          title: 'What do you want to contact us about?',
          hint: 'Select a reason',
          tag: 'feedbackType',
          required: true,
          weight: 12,
          items: FeedbackType.values // this is a normal enum
              .map((e) => SpinnerDataModel(
                    data: e.name, // I am guessing this is used to transfer the data?
                    name: e.name.capitalizeFirstOfEach,
                    id: 1,
                  ))
              .toList(),
        ),
```

Maybe I am using the widget wrongly, but as I can not use the `value` parameter I don't really know why I am only getting the instance of the class....Any help is appreciated.

**Comment by polarby** [comment]
Sorry for my mistake, I can obviously extract the data from `SpinnerDataModel` after receiving the JSON.

**Comment by toustechmobile** [comment]
Hi Paul, yes you can get dynamic `data` from `SpinnerDataModel` instance.

**Comment by toustechmobile** [comment]
Hi Paul, yes you can get dynamic `data` from `SpinnerDataModel`.
