### ISSUE TITLE
[Feature Request] Advanced Text input (Scrollable and multiline)

### ISSUE THREAD

**Issue by polarby** [ritagroup/gsform#4]
First of all, I love this package! It's way better than all the other packages that can be found on [fluttergems.dev](https://fluttergems.dev).
One thing that I am missing though is to better input text. Right now I can only use `textPlain' or `text`, but both widgets can only write in one line, which makes it very hard to write longer texts. 

I am looking for support, where the long text can be scrolled vertically and the text box resizes to a certain max height.
In the best case, there will be support for both web and mobile, while the web has this little arrow in the right bottom corner to resize the textbox (like often seen in web boxes or also on GitHub).

```dart
GSField.textPlain(
          ...
          weight: 12,
          maxLength: 500,
          maxLine: 30, // As we can only use one line this parameter is currently not useful at all
          showCounter: true,
        ),
```

Although this package is already superior, this might be a major update!

**Comment by saeeddastras** [comment]
We have fixed this issue
