### ISSUE TITLE
How to change font's size of title?

### ISSUE THREAD

**Issue by jasonchong3329** [ritagroup/gsform#5]
Hi there,

i can't find any change font size method in documentation.

May i know how to change font's size of title?
Example i want increase the font size "Amount"?

 GSField.price(
                        tag: 'product_amount',
                        title: 'Amount',
                        weight: 12,
                        hint: '20000',
                        required: true,
                        currencyName: "\$",
                        errorMessage: 'Please enter an amount',
                      )

**Comment by saeeddastras** [comment]
hi 
You can change the value of `titleStyle `in the `GSFormStyle `class  and set the desired textStyle for all fields ,as in the example below

```
GSForm.singleSection(
              context,
              fields: [
                ....
             ],
              style: GSFormStyle(
               titleStyle : const TextStyle(color: Colors.green, fontSize: 16),
              ),
            ),
```

**Comment by jasonchong3329** [comment]
> hi You can change the value of `titleStyle `in the `GSFormStyle `class and set the desired textStyle for all fields ,as in the example below
> 
> ```
> GSForm.singleSection(
>               context,
>               fields: [
>                 ....
>              ],
>               style: GSFormStyle(
>                titleStyle : const TextStyle(color: Colors.green, fontSize: 16),
>               ),
>             ),
> ```

Thank for your answer , I have solved the issue.

Another question to ask how can i display list in GSfield.spinner? getting error  : [RangeError (index): Invalid value: Not in range 0..2,

  List<SpinnerDataModel> _paybacklist2 = [];
    for (var tt in _paybacklist.data) {
      print(tt.paybackTitle);
      _paybacklist2.add(SpinnerDataModel(
        name: '7 days',
        id: 1,
      ));
    }

GSField.spinner(
                        tag: 'option',
                        required: false,
                        weight: 32,
                        title: 'option',
                        onChange: (model) {
                   
                        },
                        items: _paybacklist2,
                      ),

**Comment by jasonchong3329** [comment]
Hi
how to auto select the default value? below is not work.

                    GSField.spinner(
                        tag: 'customer_type',
                        required: false,
                        weight: 12,
                        title: 'Market type',
                        onChange: (model) {},
                        items: [
                          SpinnerDataModel(
                            name: 'Super market',
                            id: 1,
                          ),
                          SpinnerDataModel(
                              name: 'woman',
                              id: 2,
                              isSelected: true,
                              data: 'woman'),
                        ]),

**Comment by saeeddastras** [comment]
for auto select the default value 
You have to set the `isSelected `value to true in the `SpinnerDataModel `model
