### ISSUE TITLE
GSField.imagePicker Crashes

### ISSUE THREAD

**Issue by bstillitano** [ritagroup/gsform#6]
Hi there,

When using GSField.imagePicker my app crashes after I press either the 'Camera' or the 'Gallery' button on the bottom sheet that pops up. Implementation is below:

`GSField.imagePicker(tag: 'image_upload', iconWidget: const Icon(Icons.camera_alt_outlined))`

Do I need to request permissions or something like that before this will work? The exception I get is 

```
════════ Exception caught by image resource service ════════════════════════════
Exception: Invalid image data
```

**Comment by saeeddastras** [comment]
Please add the following lines to the manifest

```
<activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
```

**Comment by NomadicDeveloper22** [comment]
@saeeddastras what are the recommended steps for IOS?
