### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by polarby** [ritagroup/gsform#7]
Great plugin, but unfortunately without web support. Have to move on to another plugin, as the app is expanding to cross-platform :(

**Comment by MohammadBarati** [comment]
I am happy to inform you that we have now added web support for our Flutter package. This means that you can use our plugin not only for mobile app development but also for web development using Flutter. With the addition of web support, you can now create a seamless user experience across different platforms with ease.

If you need any assistance in getting started with our Flutter package for web development, please don't hesitate to reach out to us. We are always here to help you with any questions or concerns you may have. Thank you for choosing our plugin and we hope you enjoy the new web support feature!
